{
 "title": "iDRAC Host Stats",
 "description": "iDRAC SNMP Host Metrics",
 "tags": [
  "idrac",
  "snmp"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "idrac_host",
    "label": "iDrac Host",
    "query": {
     "query": "label_values(globalSystemStatus{job=\"prometheus-snmp-exporter\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "iDRAC Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Host Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(systemRackName{job=\"prometheus-snmp-exporter\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "query": "show tag values cardinality from \"idrac-hosts\" with key = \"system-name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Overview",
   "type": "table",
   "gridPos": { "h": 15, "w": 22, "x": 2, "y": 1 },
   "targets": [
    {
     "expr": "systemPowerState{job=\"prometheus-snmp-exporter\"} == 1",
     "groupBy": [
      { "params": [ "system-name" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-model" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "expr": "globalSystemStatus{job=\"prometheus-snmp-exporter\"} == 1",
     "groupBy": [
      { "params": [ "system-name" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "power-state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "expr": "systemServiceTag{job=\"prometheus-snmp-exporter\"}",
     "groupBy": [
      { "params": [ "system-name" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "idrac-url" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "expr": "systemModelName{job=\"prometheus-snmp-exporter\"}",
     "groupBy": [
      { "params": [ "system-name" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "limit": "1",
     "measurement": "idrac-hosts",
     "query": "SELECT \"bios-version\" FROM \"idrac-hosts\" WHERE (\"system-name\" =~ /^$idrac_host$/) AND $timeFilter GROUP BY \"system-name\" LIMIT 1",
     "select": [
      [
       { "params": [ "system-servicetag" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "expr": "firmwareVersionName{job=\"prometheus-snmp-exporter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "systemBIOSVersionName{job=\"prometheus-snmp-exporter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "systemPowerUpTime{job=\"prometheus-snmp-exporter\"}",
     "groupBy": [
      { "params": [ "system-name" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-globalstatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Scrape Failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"prometheus-snmp-exporter\"} == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Summary",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(globalSystemStatus{job=\"prometheus-snmp-exporter\", globalSystemStatus=\"ok\"})",
     "legendFormat": "Systems OK"
    },
    {
     "expr": "sum(globalSystemStatus{job=\"prometheus-snmp-exporter\", globalSystemStatus=\"critical\"})",
     "legendFormat": "Critical Failures"
    },
    {
     "expr": "sum(globalSystemStatus{job=\"prometheus-snmp-exporter\", globalSystemStatus=\"nonCritical\"})",
     "legendFormat": "Non-Critical Failures"
    }
   ]
  },
  { "title": "Host $idrac_host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "idrac_host" },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemPowerUpTime{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\"}",
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Service Tag",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemServiceTag{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\"}",
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "query": "SELECT \"system-servicetag\" FROM /^$idrac_host$/ WHERE (\"system-name\" =~ /^$idrac_host$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "system-servicetag" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Firmware Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(firmwareVersionName{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\"}) by(firmwareVersionName)",
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "bios-version" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "BIOS Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemBIOSVersionName{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\"}",
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "bios-version" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Physical Disk Status",
   "type": "table",
   "gridPos": { "h": 20, "w": 7, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "physicalDiskName{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\"}",
     "groupBy": [
      { "params": [ "disks-name" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "disks-capacity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "expr": "physicalDiskCapacityInMB{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\"} * 1048576",
     "groupBy": [
      { "params": [ "disks-name" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "disks-state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "expr": "physicalDiskState{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\"} == 1",
     "groupBy": [
      { "params": [ "disks-name" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "disks-predictivefail" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "expr": "physicalDiskSmartAlertIndication{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Interfaces",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 17 },
   "targets": [
    {
     "expr": "networkDeviceFQDD{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "networkDeviceConnectionStatus{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\"} == 1",
     "groupBy": [
      { "params": [ "nic-name" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "nic-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "expr": "networkDeviceProductName{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "networkDeviceCurrentMACAddress{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\"}",
     "groupBy": [
      { "params": [ "nic-name" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "nic-current_mac" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "OS Name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemOSName{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\"}",
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "bios-version" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Global Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "globalSystemStatus{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\"} == 1",
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "system-globalstatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Power State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemPowerState{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\"} == 1",
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "power-state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "PSU Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "powerSupplyStatus{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\"} == 1",
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "psu-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Intrusion",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "intrusionReading{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\"} == 1",
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "intrusion-sensor" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Voltage Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltageProbeDiscreteReading{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\", voltageProbeDiscreteReading!=\"voltageIsGood\"} == 1",
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "temp-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Thermal Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperatureProbeStatus{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\", temperatureProbeStatus!=\"ok\"} == 1",
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "temp-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memoryDeviceStatus{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\", memoryDeviceStatus!=\"ok\"} == 1",
     "legendFormat": "DIMM {{memoryDeviceIndex}}",
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "memory-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "globalStorageStatus{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\"} == 1",
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "storage-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "CMOS Battery",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemBatteryReading{instance=\"$idrac_host\", systemBatteryLocationName=\"System Board CMOS Battery\"} == 1",
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "cmos-batterystate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "RAID Battery",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemBatteryReading{instance=\"$idrac_host\", systemBatteryLocationName=\"PERC1 ROMB Battery\"} == 1",
     "legendFormat": "__auto",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "raid-batterystate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "System Watts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "label_replace(\n  avg_over_time(\n    amperageProbeReading{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\", amperageProbeLocationName=~\"PS\\\\d+ Current.*\"}[10m]) / 10, \"probe\", \"$1\", \"amperageProbeLocationName\", \"(PS\\\\d+).*\")\n* on(instance, probe)\nlabel_replace(\n  avg_over_time(\n    voltageProbeReading{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\", voltageProbeLocationName=~\"PS\\\\d+ Voltage.*\"}[10m]) / 1000, \"probe\", \"$1\", \"voltageProbeLocationName\", \"(PS\\\\d+).*\")",
     "legendFormat": "{{probe}}"
    }
   ]
  },
  {
   "title": "System Log Entries",
   "type": "table",
   "gridPos": { "h": 31, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "eventLogDateName{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "eventLogRecord{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\"}",
     "groupBy": [
      { "params": [ "log-number" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "limit": "1",
     "measurement": "idrac-hosts",
     "query": "SELECT \"log-dates\" FROM \"idrac-hosts\" WHERE (\"system-name\" =~ /^$idrac_host$/) AND $timeFilter GROUP BY \"log-number\" LIMIT 1",
     "select": [
      [
       { "params": [ "log-dates" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "expr": "eventLogSeverityStatus_info{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\"}",
     "groupBy": [
      { "params": [ "log-number" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "log-entry" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "CPU 1 Temp",
     "expr": "avg_over_time(temperatureProbeReading{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\", temperatureProbeLocationName=~\"CPU.*\"}[30m]) / 10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "{{temperatureProbeLocationName}}",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "cpu1-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "DIMM Status",
   "type": "table",
   "gridPos": { "h": 19, "w": 7, "x": 8, "y": 37 },
   "targets": [
    {
     "expr": "memoryDeviceSize{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\"}",
     "groupBy": [
      { "params": [ "disks-name" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "disks-predictivefail" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "expr": "memoryDeviceStatus{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\"} == 1",
     "groupBy": [
      { "params": [ "disks-name" ], "type": "tag" }
     ],
     "legendFormat": "__auto",
     "limit": "1",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "disks-capacity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Air Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Inlet Temp",
     "expr": "avg_over_time(temperatureProbeReading{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\", temperatureProbeLocationName=~\"System Board Inlet Temp|System Board Exhaust Temp\"}[30m]) / 10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "{{temperatureProbeLocationName}}",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "inlet-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "alias": "Fan 1",
     "expr": "avg_over_time(coolingDeviceReading{job=\"prometheus-snmp-exporter\", instance=\"$idrac_host\"}[30m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "{{coolingDeviceLocationName}}",
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan1-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  }
 ]
}